on:
  pull_request:
    types:
      - labeled

name: Validate Experience

jobs:
  validate-experience:
    if: github.event.pull_request.label == 'new-experience'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Resolve experience name
        run: |
          echo ${{ github.event.pull_request.branch }}
          echo "experience_name=$(echo ${{ github.event.pull_request.branch }} | cut -d' ' -f2)" >> "$GITHUB_ENV"
      - name: Run validator
        run: |
          ./cli/usecasevalidator -path experiences/${{ env.experience_name }}/${{ env.experience_name }}.zip -creator -r -validate